### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by foobnix** [TheMusicmax/Musicmax#470]
Process: com.maximillianleonov.musicmax, PID: 17076
                                                                                                    java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~5XWP1kghMjTuXVGSSXBJUg==/com.maximillianleonov.musicmax-EDp3bv-eAKqI7bSc49_meQ==/base.apk)
                                                                                                    	at com.maximillianleonov.musicmax.core.ui.component.MediaHeaderKt$SortButton$1.invoke(MediaHeader.kt:233)
                                                                                                    	at com.maximillianleonov.musicmax.core.ui.component.MediaHeaderKt$SortButton$1.invoke(MediaHeader.kt:232)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material3.IconButtonKt.IconButton(IconButton.kt:101)
                                                                                                    	at com.maximillianleonov.musicmax.core.ui.component.MediaHeaderKt.SortButton(MediaHeader.kt:232)
                                                                                                    	at com.maximillianleonov.musicmax.core.ui.component.MediaHeaderKt.OutlinedMediaHeader(MediaHeader.kt:166)
                                                                                                    	at com.maximillianleonov.musicmax.core.ui.component.MediaPagerKt$MediaPager$1$3.invoke(MediaPager.kt:102)
                                                                                                    	at com.maximillianleonov.musicmax.core.ui.component.MediaPagerKt$MediaPager$1$3.invoke(MediaPager.kt:101)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:941)
                                                                                                    	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:277)
                                                                                                    	at com.maximillianleonov.musicmax.core.ui.component.MediaPagerKt.MediaPager(MediaPager.kt:101)
                                                                                                    	at com.maximillianleonov.musicmax.feature.home.HomeScreenKt.HomeScreen(HomeScreen.kt:86)
                                                                                                    	at com.maximillianleonov.musicmax.feature.home.HomeScreenKt.HomeRoute(HomeScreen.kt:44)
                                                                                                    	at com.maximillianleonov.musicmax.feature.home.navigation.HomeNavigationKt$homeScreen$1$1.invoke(HomeNavigation.kt:35)
                                                                                                    	at com.maximillianleonov.musicmax.feature.home.navigation.HomeNavigationKt$homeScreen$1$1.invoke(HomeNavigation.kt:34)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.navigation.compose.NavGraphBuilderKt$composable$1.invoke(NavGraphBuilder.kt:53)
                                                                                                    	at androidx.navigation.compose.NavGraphBuilderKt$composable$1.invoke(NavGraphBuilder.kt:51)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:308)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:306)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)

**Comment by AfigAliyev** [comment]
Thank you for the report!
